/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ujmd.formularios;

import edu.ujmd.veterinaria.controladores.CitasJpaController;
import edu.ujmd.veterinaria.controladores.ClientesJpaController;
import edu.ujmd.veterinaria.controladores.EmpleadosJpaController;
import edu.ujmd.veterinaria.entidades.Citas;
import edu.ujmd.veterinaria.entidades.Clientes;
import edu.ujmd.veterinaria.entidades.Empleados;
import edu.ujmd.veterinaria.entidades.Mascotas;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meev9
 */
public class frmCitas extends javax.swing.JFrame {

    //Conectamos a la base de datos
    CitasJpaController controlcit = new CitasJpaController();
    EmpleadosJpaController controlemp = new EmpleadosJpaController();
    ClientesJpaController controlcli = new ClientesJpaController();

    //Entidades
    Citas entici = new Citas();
    Empleados entiem = new Empleados();
    Clientes enticli = new Clientes();

    public void cargar() {
        entici.setFechaHora(this.calendarcita.getDate());
        enticli.setCodClientes(cboCliente.getSelectedIndex() + 1);
        entici.setCodClientes(enticli);
        entiem.setCodEmpleados(cboEmpleado.getSelectedIndex() + 1);
        entici.setCodEmpleados(entiem);

    }

    public void limpiar() {
        this.lblcodigo.setText("Generado Automaticamente");
        this.cboCliente.setSelectedIndex(0);
        this.cboEmpleado.setSelectedIndex(0);
    }

    public void llenarTabla() {
        String col[] = {"ID", "CLIENTE", "EMPLEADO", "FECHA"};
        DefaultTableModel modelo = new DefaultTableModel(col, 0);
        Object[] obj = new Object[5];
        List ls;

        try {
            ls = controlcit.findCitasEntities();
            for (int i = 0; i < ls.size(); i++) {
                entici = (Citas) ls.get(i);
                obj[0] = entici.getCodCitas();
                obj[1] = entici.getCodClientes().getNombre();
                obj[2] = entici.getCodEmpleados().getNombre();
                obj[3] = entici.getFechaHora();

                modelo.addRow(obj);
            }
            this.tablacitas.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos : " + e.getMessage());
        }

    }

    /**
     * Creates new form frmCitas
     */
    public frmCitas() {
        initComponents();
        llenarComboClientes();
        llenarComboEmpleados();
        llenarTabla();
    }
    List litsCliente = null;
    List litsEmpleado = null;

    public void llenarComboClientes() {
        try {
            litsCliente = controlcli.findClientesEntities();
            for (int i = 0; i < litsCliente.size(); i++) {
                enticli = (Clientes) litsCliente.get(i);
                cboCliente.addItem(enticli.getNombre());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos : " + e.getMessage());
        }
    }

    public void llenarComboEmpleados() {
        try {
            litsEmpleado = controlemp.findEmpleadosEntities();
            for (int i = 0; i < litsEmpleado.size(); i++) {
                entiem = (Empleados) litsEmpleado.get(i);
                cboEmpleado.addItem(entiem.getNombre());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos : " + e.getMessage());
        }
    }

    public int buscarComboClientes(String depto) {
        int index = 0;
        try {
            for (int i = 0; i < litsCliente.size(); i++) {
                enticli = (Clientes) litsCliente.get(i);
                if (enticli.getCodClientes().equals(depto)) {
                    index = i;
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos : " + e.getMessage());
        }
        return index;
    }

    public int buscarComboEmpleados(String dep) {
        int index = 0;
        try {
            for (int i = 0; i < litsEmpleado.size(); i++) {
                entiem = (Empleados) litsEmpleado.get(i);
                if (entiem.getCodEmpleados().equals(dep)) {
                    index = i;
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos : " + e.getMessage());
        }
        return index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablacitas = new javax.swing.JTable();
        txtEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnVolver2 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        btnModifica = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboEmpleado = new javax.swing.JComboBox<>();
        cboCliente = new javax.swing.JComboBox<>();
        calendarcita = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        tablacitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablacitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacitas);

        txtEliminar.setText("Eliminar");
        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("CODIGO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CITAS");

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));

        btnVolver2.setText("Volver al menu");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("EMPLEADO");

        lblcodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcodigo.setText("Se genera automaticamente");

        btnModifica.setText("Modificar");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        jLabel6.setText("FECHA Y HORA");

        jLabel3.setText("CLIENTE");

        cboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(605, 605, 605)
                        .addComponent(txtEliminar)
                        .addGap(62, 62, 62)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblcodigo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(btnModifica))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calendarcita, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(557, 557, 557)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnModifica))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnVolver2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEliminar)
                                    .addComponent(btnLimpiar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(lblcodigo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(calendarcita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablacitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacitasMouseClicked
        this.lblcodigo.setText(tablacitas.getValueAt(tablacitas.getSelectedRow(), 0).toString());
        int index = 0;
        index = buscarComboClientes(tablacitas.getValueAt(tablacitas.getSelectedRow(), 1).toString());
        this.cboCliente.setSelectedIndex(index);
        index = buscarComboEmpleados(tablacitas.getValueAt(tablacitas.getSelectedRow(), 2).toString());
        this.cboEmpleado.setSelectedIndex(index);
    }//GEN-LAST:event_tablacitasMouseClicked

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        boolean delete = true;
        try {
            cargar();
            entici.setCodCitas(Integer.parseInt(this.lblcodigo.getText()));
            controlcit.destroy(entici.getCodCitas());
        } catch (Exception ex) {
            delete = false;
            JOptionPane.showMessageDialog(this, "Error en eliminar registro : " + ex.getMessage());
        }
        if (delete) {
            limpiar();
            llenarTabla();
            JOptionPane.showMessageDialog(this, "El Registro se elimino con Exito!!!");
        }
    }//GEN-LAST:event_txtEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        frmMenu menu = new frmMenu();
        menu.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        boolean save = true;
        try {
            cargar();
            controlcit.create(entici);
        } catch (Exception ex) {
            save = false;
            JOptionPane.showMessageDialog(this, "Error en almacenar registro : " + ex.getMessage());
        }
        if (save) {
            limpiar();
            llenarTabla();
            JOptionPane.showMessageDialog(this, "El Registro se guardo con Exito!!!");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        boolean update = true;
        try {
            cargar();
            entici.setCodCitas(Integer.parseInt(this.lblcodigo.getText()));
            controlcit.edit(entici);
        } catch (Exception ex) {
            update = false;
            JOptionPane.showMessageDialog(this, "Error en actualizar registro : " + ex.getMessage());
        }
        if (update) {
            limpiar();
            llenarTabla();
            JOptionPane.showMessageDialog(this, "El Registro se actualizo con Exito!!!");
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnVolver2;
    private com.toedter.calendar.JDateChooser calendarcita;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tablacitas;
    private javax.swing.JButton txtEliminar;
    // End of variables declaration//GEN-END:variables
}
